"""add sentiment_posts and sentiment_results

Revision ID: 8e583d823794
Revises: 578ee9896289
Create Date: 2026-08-01 13:58:47.723922

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8e583d823794'
down_revision: str | Sequence[str] | None = '578ee9896289'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('publish_time', sa.String(length=50), nullable=True),
    sa.Column('engagement', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_posts_id'), 'sentiment_posts', ['id'], unique=False)
    op.create_index(op.f('ix_sentiment_posts_keyword'), 'sentiment_posts', ['keyword'], unique=False)
    op.create_table('sentiment_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['sentiment_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_results_id'), 'sentiment_results', ['id'], unique=False)
    op.create_index(op.f('ix_sentiment_results_post_id'), 'sentiment_results', ['post_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_results_post_id'), table_name='sentiment_results')
    op.drop_index(op.f('ix_sentiment_results_id'), table_name='sentiment_results')
    op.drop_table('sentiment_results')
    op.drop_index(op.f('ix_sentiment_posts_keyword'), table_name='sentiment_posts')
    op.drop_index(op.f('ix_sentiment_posts_id'), table_name='sentiment_posts')
    op.drop_table('sentiment_posts')
    # ### end Alembic commands ###
